[build]
  command = "npm run build"
  
[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"

# Force Netlify to use this configuration
[build.processing]
  skip_processing = false
